#!/bin/bash

bash train_and_eval.sh WaveUNet_L1 WaveUNet L1Loss PhaseShuffleRandomizer
bash train_and_eval.sh WaveUNet_Smooth_L1 WaveUNet SmoothL1Loss PhaseShuffleRandomizer

bash train_and_eval.sh Autoencoder_L1_SampleShuffle Conv1DAutoencoder L1Loss SampleShuffleRandomizer
bash train_and_eval.sh Autoencoder_Smooth_L1_SampleShuffle Conv1DAutoencoder SmoothL1Loss SampleShuffleRandomizer

bash train_and_eval.sh Autoencoder_L1 Conv1DAutoencoder L1Loss PhaseShuffleRandomizer
bash train_and_eval.sh Autoencoder_Smooth_L1 Conv1DAutoencoder SmoothL1Loss PhaseShuffleRandomizer

bash train_and_eval.sh ShuffleAutoencoder_L1 PixelShuffleConv1DAutoencoder L1Loss PhaseShuffleRandomizer
bash train_and_eval.sh ShuffleAutoencoder_Smooth_L1 PixelShuffleConv1DAutoencoder SmoothL1Loss PhaseShuffleRandomizer

bash train_and_eval.sh TransformerShuffleAutoencoder_L1 PixelShuffleConv1DAutoencoderWithTransformer L1Loss PhaseShuffleRandomizer
bash train_and_eval.sh TransformerShuffleAutoencoder_Smooth_L1 PixelShuffleConv1DAutoencoderWithTransformer SmoothL1Loss PhaseShuffleRandomizer