defaults:
  - train: simple
  - eval: simple
  - data: raw240517
  - model: wave_u_net_enhance_transformer
  - loss_fn: weighted_l1
  - randomizer: add_uniform_noise
  - secret: none
  - logging: local
  - hydra: run
  - debug: default
  - _self_

mode: train

